%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /home/ljf/code/00

# camera intrinsics
# fr1
camera.fx: 718.856
camera.fy: 718.856
camera.cx: 607.1928
camera.cy: 185.2157

camera.depth_scale: 5000

# VO paras
# number_of_features: 500
number_of_features: 200
scale_factor: 1.2
local_map_size: 3
level_pyramid: 8
match_ratio: 1.8
match_ratio_inmap: 15
max_num_lost: 10
min_inliers: 5
keyframe_rotation: 0.1
keyframe_translation: 0.1
